import { formatMoney } from "@/domain/ui/journey";
import type { MoneyDto } from "@/domain/money";
import type { PaymentFailureCategory } from "@/domain/payment/failure";
import type { PolicyDecisionKind } from "@/domain/policy/decision";
import type { TransactionState } from "@/domain/transaction/states";

/**
 * The Agentic Purchase Safety Passport: one panel that answers "why was this
 * AI-assisted purchase safe?" from facts the server already holds.
 *
 * Everything in this file is pure. It takes rows that have already been read -
 * a transaction's state, its quotes, its policy evaluation, its approvals, its
 * stock holds, its payment attempts and its audit trail - and turns them into
 * labelled statuses. It reads no database, calls no provider, and has no clock
 * of its own.
 *
 * ## Why a model is not allowed anywhere near it
 *
 * The passport's entire value is that a reviewer can believe it. A sentence
 * generated by a language model is a plausible sentence, not evidence, and a
 * safety summary that a model wrote would be exactly the artefact this system
 * spends seventeen states avoiding: a confident claim with nothing underneath
 * it. So no branch below takes model output as an input, and there is nowhere
 * for one to be added - the fact type carries persisted values only.
 *
 * ## The rule every branch obeys
 *
 * A positive claim requires evidence for that specific claim. "Captured" is
 * never inferred from a verified callback, "committed" is never inferred from a
 * capture, and "exactly once" is never inferred from a single current row -
 * because a row shows the present, and "once" is a statement about history. The
 * counts taken from the audit trail are what make those distinctions decidable,
 * and where the evidence is absent the honest status is `NOT_REACHED` rather
 * than a blank space that a reader would take for a pass.
 *
 * ## What it is not
 *
 * Not a replacement for the audit timeline. The timeline is the chronological
 * evidence; this is the summary a reviewer reads first. It also makes no
 * absolute claims - nothing here says "secure", "guaranteed" or "fraud-proof",
 * because those are not facts about a transaction. Verified, bounded,
 * authorized, captured, committed and deduplicated are.
 */

// ---------------------------------------------------------------------------
// Vocabulary
// ---------------------------------------------------------------------------

/**
 * Every status a passport line may carry.
 *
 * Closed on purpose. A free-text status invites "looks fine", and a status a
 * reader cannot enumerate is a status they cannot check.
 */
export const PASSPORT_STATUSES = [
  "VERIFIED",
  "ALLOWED",
  "REQUIRED",
  "APPROVED",
  "REJECTED",
  "NOT_REQUIRED",
  "RESERVED",
  "COMMITTED",
  "RELEASED",
  "CAPTURED",
  "DEDUPLICATED",
  "PENDING",
  "FAILED",
  "BLOCKED",
  "EXPIRED",
  "STOPPED",
  "COMPLETED",
  "NOT_REACHED",
  "NONE",
] as const;

export type PassportStatus = (typeof PASSPORT_STATUSES)[number];

const STATUS_LABELS: Readonly<Record<PassportStatus, string>> = {
  VERIFIED: "Verified",
  ALLOWED: "Allowed",
  REQUIRED: "Required",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  NOT_REQUIRED: "Not required",
  RESERVED: "Reserved",
  COMMITTED: "Committed",
  RELEASED: "Released",
  CAPTURED: "Captured",
  DEDUPLICATED: "Deduplicated",
  PENDING: "Pending",
  FAILED: "Failed",
  BLOCKED: "Blocked",
  EXPIRED: "Expired",
  STOPPED: "Stopped",
  COMPLETED: "Completed",
  NOT_REACHED: "Not reached",
  NONE: "None",
};

/** Drives styling only. Deliberately the same four words the journey uses. */
export type PassportTone = "POSITIVE" | "NEUTRAL" | "WARNING" | "NEGATIVE";

/**
 * The tone each status carries when nothing overrides it.
 *
 * `NOT_REQUIRED`, `NONE` and `NOT_REACHED` are neutral rather than positive: a
 * step that did not happen is a fact, not an achievement, and painting it green
 * would make an unfinished purchase look like a finished one.
 */
const STATUS_TONES: Readonly<Record<PassportStatus, PassportTone>> = {
  VERIFIED: "POSITIVE",
  ALLOWED: "POSITIVE",
  REQUIRED: "WARNING",
  APPROVED: "POSITIVE",
  REJECTED: "NEGATIVE",
  NOT_REQUIRED: "NEUTRAL",
  RESERVED: "POSITIVE",
  COMMITTED: "POSITIVE",
  RELEASED: "NEUTRAL",
  CAPTURED: "POSITIVE",
  DEDUPLICATED: "POSITIVE",
  PENDING: "WARNING",
  FAILED: "NEGATIVE",
  BLOCKED: "NEGATIVE",
  EXPIRED: "WARNING",
  STOPPED: "NEGATIVE",
  COMPLETED: "POSITIVE",
  NOT_REACHED: "NEUTRAL",
  NONE: "NEUTRAL",
};

// ---------------------------------------------------------------------------
// The facts this is built from
// ---------------------------------------------------------------------------

/** One payment attempt, as persisted. Nothing here comes from a browser. */
export interface PassportAttemptFact {
  readonly attemptNumber: number;
  /** `PaymentAttemptStatus`, verbatim from the row. */
  readonly status: string;
  readonly amount: MoneyDto;
  readonly failureCategory: PaymentFailureCategory | null;
}

/** One quote, as persisted. */
export interface PassportQuoteFact {
  readonly status: string;
  readonly totalAmount: MoneyDto;
}

/**
 * How many times each audited fact was recorded for this transaction.
 *
 * Counts rather than booleans, because several of the claims below are claims
 * about *how many times* something happened. "Committed exactly once" cannot be
 * decided from a boolean, and deciding it from the single current reservation
 * row would be deciding a question about history from the present tense.
 */
export interface PassportEvidence {
  readonly productVerified: number;
  readonly productSelectionRejected: number;
  readonly quoteCreated: number;
  readonly quoteReissued: number;
  readonly policyEvaluated: number;
  readonly approvalGranted: number;
  readonly approvalDenied: number;
  readonly inventoryReserved: number;
  readonly inventoryRequoted: number;
  readonly inventoryCommitted: number;
  readonly paymentVerified: number;
  readonly paymentCaptured: number;
  readonly paymentFailed: number;
  readonly callbackRejected: number;
  readonly retryRequested: number;
  readonly webhookDuplicate: number;
  readonly webhookMismatch: number;
  readonly multipleCaptureDetected: number;
  /** Lifecycle moves recorded by the state machine. */
  readonly stateTransitions: number;
  /** Audited decisions, excluding lifecycle moves. */
  readonly auditedFacts: number;
}

export interface SafetyPassportFacts {
  readonly transactionId: string;
  readonly state: TransactionState;

  /**
   * The amount this purchase is actually about, taken from a quote row.
   *
   * Null before any quote exists. Never taken from a payment attempt, a request
   * body or a live product row - the quote is the one place a payable amount
   * lives in this system.
   */
  readonly trustedAmount: MoneyDto | null;
  /** The status of the quote that amount came from. */
  readonly trustedQuoteStatus: string | null;
  /** Whether that quote could still be used to start a payment right now. */
  readonly quoteUsable: boolean;
  /** Every quote this transaction has ever had. */
  readonly quotes: readonly PassportQuoteFact[];

  readonly policyDecision: PolicyDecisionKind | null;
  readonly policyReasonCode: string | null;

  /** `ApprovalStatus` values, verbatim. */
  readonly approvalStatuses: readonly string[];
  /** `InventoryReservationStatus` values, verbatim. */
  readonly reservationStatuses: readonly string[];

  readonly attempts: readonly PassportAttemptFact[];
  readonly maxAttempts: number;
  /** Server-computed retry eligibility. Null when no payment path ever opened. */
  readonly retryAvailable: boolean | null;
  readonly retryDenial: string | null;

  readonly evidence: PassportEvidence;
}

// ---------------------------------------------------------------------------
// The view model
// ---------------------------------------------------------------------------

export const PASSPORT_CHECK_IDS = [
  "AI_BOUNDED",
  "PRICE_VERIFIED",
  "POLICY",
  "HUMAN_APPROVAL",
  "INVENTORY",
  "PAYMENT_AMOUNT",
  "CALLBACK_VERIFIED",
  "PROVIDER_CAPTURE",
  "INVENTORY_COMMITTED",
  "TRANSACTION",
] as const;

export type PassportCheckId = (typeof PASSPORT_CHECK_IDS)[number];

export interface PassportCheck {
  readonly id: PassportCheckId;
  readonly label: string;
  readonly status: PassportStatus;
  readonly statusLabel: string;
  readonly tone: PassportTone;
  /** The concrete fact under the label: an amount, a decision, a state. */
  readonly value: string;
  /** One short factual sentence, or null when the value says it all. */
  readonly note: string | null;
}

/** A line in the retry section. Same shape for an attempt and for a safeguard. */
export interface PassportRow {
  readonly label: string;
  readonly value: string;
  readonly tone: PassportTone;
}

/** One of the five properties, with the evidence that supports it here. */
export interface PassportProperty {
  readonly label: string;
  /** True only when this transaction's own records support the property. */
  readonly evidenced: boolean;
  readonly evidence: string;
}

export interface PassportAuthority {
  readonly label: string;
  readonly value: string;
  readonly note: string;
}

export interface SafetyPassportViewModel {
  readonly transactionId: string;
  readonly title: string;
  readonly subtitle: string;
  readonly aiAuthority: PassportAuthority;
  readonly financialAuthority: PassportAuthority;
  readonly priceSource: string;
  readonly checks: readonly PassportCheck[];
  /** Present only when there is genuine retry, re-quote or replay history. */
  readonly retry: {
    readonly attemptsUsed: number;
    readonly maxAttempts: number;
    readonly rows: readonly PassportRow[];
  } | null;
  readonly properties: readonly PassportProperty[];
}

// ---------------------------------------------------------------------------
// Reading the audit trail into counts
// ---------------------------------------------------------------------------

/** The only shape this module needs from a timeline entry. */
export interface PassportTimelineEntry {
  readonly action: string;
}

const EMPTY_EVIDENCE: PassportEvidence = {
  productVerified: 0,
  productSelectionRejected: 0,
  quoteCreated: 0,
  quoteReissued: 0,
  policyEvaluated: 0,
  approvalGranted: 0,
  approvalDenied: 0,
  inventoryReserved: 0,
  inventoryRequoted: 0,
  inventoryCommitted: 0,
  paymentVerified: 0,
  paymentCaptured: 0,
  paymentFailed: 0,
  callbackRejected: 0,
  retryRequested: 0,
  webhookDuplicate: 0,
  webhookMismatch: 0,
  multipleCaptureDetected: 0,
  stateTransitions: 0,
  auditedFacts: 0,
};

/** Which audit event type feeds which counter. Anything unlisted is ignored. */
const EVIDENCE_OF: Readonly<Record<string, keyof PassportEvidence>> = {
  product_verified: "productVerified",
  product_selection_rejected: "productSelectionRejected",
  quote_created: "quoteCreated",
  quote_reissued: "quoteReissued",
  policy_evaluated: "policyEvaluated",
  approval_granted: "approvalGranted",
  approval_denied: "approvalDenied",
  inventory_reserved: "inventoryReserved",
  inventory_reservation_requoted: "inventoryRequoted",
  inventory_committed: "inventoryCommitted",
  payment_verified: "paymentVerified",
  payment_captured: "paymentCaptured",
  payment_failed: "paymentFailed",
  payment_callback_rejected: "callbackRejected",
  payment_retry_requested: "retryRequested",
  webhook_duplicate: "webhookDuplicate",
  webhook_mismatch: "webhookMismatch",
  payment_multiple_capture_detected: "multipleCaptureDetected",
};

/**
 * Counts what the trail actually contains.
 *
 * Deliberately tolerant of unknown action names: the audited vocabulary grows
 * with every objective, and a passport that threw on an event type it had not
 * been taught would turn a new audit record into a broken page.
 */
export function countPassportEvidence(
  entries: readonly PassportTimelineEntry[],
): PassportEvidence {
  const counts: Record<keyof PassportEvidence, number> = { ...EMPTY_EVIDENCE };
  for (const entry of entries) {
    if (entry.action === "state_transitioned") {
      counts.stateTransitions += 1;
      continue;
    }
    counts.auditedFacts += 1;
    const key = EVIDENCE_OF[entry.action];
    if (key !== undefined) counts[key] += 1;
  }
  return counts;
}

// ---------------------------------------------------------------------------
// Building the passport
// ---------------------------------------------------------------------------

/** States in which nothing further will happen without a new purchase. */
const HALTED: ReadonlySet<TransactionState> = new Set([
  "BLOCKED",
  "CANCELLED",
  "EXPIRED",
]);

/** Approval statuses that mean a person said yes. */
const APPROVED_STATUSES: ReadonlySet<string> = new Set(["APPROVED", "CONSUMED"]);

function check(
  id: PassportCheckId,
  label: string,
  status: PassportStatus,
  value: string,
  note: string | null = null,
  tone: PassportTone = STATUS_TONES[status],
): PassportCheck {
  return { id, label, status, statusLabel: STATUS_LABELS[status], tone, value, note };
}

function aiBoundedCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "AI selection bounded to merchant catalog";
  if (facts.evidence.productVerified > 0) {
    return check(
      "AI_BOUNDED",
      label,
      "VERIFIED",
      "Proposal re-read from the catalog",
      "The server looked the proposed product up in the merchant's own records before any price existed.",
    );
  }
  if (facts.evidence.productSelectionRejected > 0) {
    return check(
      "AI_BOUNDED",
      label,
      "BLOCKED",
      "Proposal refused",
      "The assistant proposed something the server would not verify, so no quote was issued.",
    );
  }
  return check("AI_BOUNDED", label, "NOT_REACHED", "No proposal verified yet");
}

function priceCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Price verified by server";
  if (facts.trustedAmount === null) {
    const quoted = facts.quotes.length > 0;
    return check(
      "PRICE_VERIFIED",
      label,
      quoted ? "EXPIRED" : "NOT_REACHED",
      quoted ? "No live quote" : "No quote yet",
      quoted
        ? "Every quote issued for this purchase has been superseded or invalidated."
        : null,
    );
  }

  const status = facts.trustedQuoteStatus ?? "UNKNOWN";
  return check(
    "PRICE_VERIFIED",
    label,
    "VERIFIED",
    `${formatMoney(facts.trustedAmount)} ${facts.trustedAmount.currency}`,
    facts.quoteUsable
      ? `Quote ${status.toLowerCase()}. This is the only amount that can be charged.`
      : `Quote ${status.toLowerCase()}, and no longer usable to start a new payment.`,
  );
}

function policyCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Spending policy evaluated";
  if (facts.policyDecision === null) {
    return check("POLICY", label, "NOT_REACHED", "Not evaluated yet");
  }
  const status: PassportStatus =
    facts.policyDecision === "ALLOWED"
      ? "ALLOWED"
      : facts.policyDecision === "APPROVAL_REQUIRED"
        ? "REQUIRED"
        : "BLOCKED";
  return check(
    "POLICY",
    label,
    status,
    facts.policyDecision,
    facts.policyReasonCode === null ? null : `Reason code ${facts.policyReasonCode}.`,
  );
}

function approvalCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Human approval";
  const approved = facts.approvalStatuses.filter((s) => APPROVED_STATUSES.has(s)).length;

  if (approved > 0) {
    // "Once" is a claim about history, so it needs the audit count as well as
    // the row count. With more than one of either, the honest word is "approved"
    // with the counts said out loud.
    const once = approved === 1 && facts.evidence.approvalGranted === 1;
    return check(
      "HUMAN_APPROVAL",
      label,
      "APPROVED",
      once ? "Approved once" : "Approved",
      once
        ? "One scoped, single-use approval was granted for this exact amount."
        : `${String(approved)} approvals are recorded for this purchase.`,
      once ? "POSITIVE" : "WARNING",
    );
  }
  if (facts.approvalStatuses.includes("REJECTED")) {
    return check(
      "HUMAN_APPROVAL",
      label,
      "REJECTED",
      "Rejected by the buyer",
      "Nothing was charged.",
    );
  }
  if (facts.approvalStatuses.includes("PENDING")) {
    return check(
      "HUMAN_APPROVAL",
      label,
      "REQUIRED",
      "Waiting for a person",
      "No payment can start until this is answered.",
    );
  }
  if (facts.approvalStatuses.includes("EXPIRED")) {
    return check(
      "HUMAN_APPROVAL",
      label,
      "EXPIRED",
      "Approval window closed",
      "The approval expired before it was answered.",
    );
  }
  if (facts.policyDecision === "APPROVAL_REQUIRED") {
    return check(
      "HUMAN_APPROVAL",
      label,
      "REQUIRED",
      "Required, not yet requested",
      "The verified total is above the automatic limit, so a person has to decide.",
    );
  }
  if (facts.policyDecision === "ALLOWED") {
    return check(
      "HUMAN_APPROVAL",
      label,
      "NOT_REQUIRED",
      "Not required",
      "The verified total was inside the policy ceiling, so no approval was demanded.",
    );
  }
  return check("HUMAN_APPROVAL", label, "NOT_REACHED", "Not reached");
}

function inventoryCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Inventory reservation";
  const statuses = facts.reservationStatuses;

  // Claimed only when there is exactly one hold to have reused, and an audit
  // record saying it was rebound. Two holds would make "reused" a guess.
  const reused =
    facts.evidence.inventoryRequoted > 0 && statuses.length === 1
      ? "The original hold was rebound to the freshly quoted price rather than a second hold being taken."
      : null;

  if (statuses.includes("COMMITTED")) {
    return check("INVENTORY", label, "COMMITTED", "COMMITTED", reused);
  }
  if (statuses.includes("ACTIVE")) {
    return check(
      "INVENTORY",
      label,
      "RESERVED",
      "ACTIVE",
      reused ?? "Stock is held for this purchase while payment is attempted.",
    );
  }
  if (statuses.includes("RELEASED")) {
    return check(
      "INVENTORY",
      label,
      "RELEASED",
      "RELEASED",
      "The hold was given back, so the stock is available to others again.",
    );
  }
  if (statuses.includes("EXPIRED")) {
    return check(
      "INVENTORY",
      label,
      "EXPIRED",
      "EXPIRED",
      "The hold ran out before payment completed.",
    );
  }
  return check("INVENTORY", label, "NOT_REACHED", "No hold taken");
}

function paymentAmountCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Payment amount controlled by server";
  if (facts.attempts.length === 0) {
    return check("PAYMENT_AMOUNT", label, "NOT_REACHED", "No payment attempted");
  }

  // The whole claim, made decidable: every attempt's amount must be an amount
  // this transaction actually quoted. Both sides are persisted rows, so nothing
  // a browser sent can satisfy it.
  const quoted = new Set(
    facts.quotes.map((q) => `${q.totalAmount.amountMinor}:${q.totalAmount.currency}`),
  );
  const unmatched = facts.attempts.filter(
    (attempt) => !quoted.has(`${attempt.amount.amountMinor}:${attempt.amount.currency}`),
  );

  if (unmatched.length > 0) {
    return check(
      "PAYMENT_AMOUNT",
      label,
      "BLOCKED",
      "Does not match a quote",
      "A payment attempt carries an amount this transaction never quoted. This needs a person.",
    );
  }

  const last = facts.attempts[facts.attempts.length - 1];
  const count = String(facts.attempts.length);
  return check(
    "PAYMENT_AMOUNT",
    label,
    "VERIFIED",
    last === undefined ? "Verified" : formatMoney(last.amount),
    `All ${count} of ${count} payment attempts carry an amount this server quoted.`,
  );
}

function callbackCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Razorpay callback verification";
  if (facts.evidence.paymentVerified > 0) {
    return check(
      "CALLBACK_VERIFIED",
      label,
      "VERIFIED",
      "Signature authentic",
      "The browser's confirmation carried a valid signature. That proves the message is genuine, not that money moved.",
    );
  }
  if (facts.evidence.callbackRejected > 0) {
    return check(
      "CALLBACK_VERIFIED",
      label,
      "BLOCKED",
      "Callback refused",
      "A checkout callback failed its signature or relationship checks and was not acted on.",
    );
  }
  // The browser's confirmation is an optimisation, not the source of truth, and
  // once the provider has confirmed settlement out of band it is no longer
  // outstanding - it is simply not part of how this purchase concluded.
  //
  // Saying "PENDING - no confirmation yet" here was wrong in a specific and
  // alarming way: the two messages race, and a webhook that arrives before the
  // browser returns (or a browser that never returns at all, because the tab was
  // closed on the provider's page) settles the purchase without one. The panel
  // then showed a permanent warning beside a captured, committed, completed
  // transaction, implying something was still unresolved when nothing was.
  //
  // This is deliberately NOT a claim that the callback was verified. The
  // signature was never checked because no callback arrived, and reporting this
  // as VERIFIED would merge browser evidence with provider evidence - the one
  // distinction this row exists to preserve. `NOT_REQUIRED` states the true
  // fact: the step did not happen, and did not need to.
  if (hasCapture(facts)) {
    return check(
      "CALLBACK_VERIFIED",
      label,
      "NOT_REQUIRED",
      "Not needed",
      "Razorpay confirmed this payment directly, so the browser's confirmation was never needed. Settlement is proven by the provider's own event, below.",
    );
  }
  if (facts.attempts.length > 0 && !HALTED.has(facts.state)) {
    return check("CALLBACK_VERIFIED", label, "PENDING", "No confirmation yet");
  }
  return check("CALLBACK_VERIFIED", label, "NOT_REACHED", "Not reached");
}

/** The newest recorded failure category, as a readable phrase. */
function lastFailure(facts: SafetyPassportFacts): string | null {
  for (let i = facts.attempts.length - 1; i >= 0; i -= 1) {
    const category = facts.attempts[i]?.failureCategory;
    if (category !== null && category !== undefined) {
      return category.replace(/_/g, " ").toLowerCase();
    }
  }
  return null;
}

/** True only on capture evidence. A verified callback is never enough. */
function hasCapture(facts: SafetyPassportFacts): boolean {
  return (
    facts.evidence.paymentCaptured > 0 ||
    facts.attempts.some((attempt) => attempt.status === "CAPTURED")
  );
}

function captureCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Provider capture confirmation";
  const doubled = facts.evidence.multipleCaptureDetected > 0;

  if (hasCapture(facts)) {
    return check(
      "PROVIDER_CAPTURE",
      label,
      "CAPTURED",
      "Settlement confirmed",
      doubled
        ? "More than one captured payment is recorded for this purchase and has been flagged for review."
        : "Razorpay confirmed the payment out of band. This, and only this, is money.",
      doubled ? "NEGATIVE" : "POSITIVE",
    );
  }
  if (facts.state === "PAYMENT_VERIFIED") {
    return check(
      "PROVIDER_CAPTURE",
      label,
      "PENDING",
      "Awaiting the provider",
      "The callback was verified. Settlement is not confirmed, so this is not treated as paid.",
    );
  }
  if (facts.state === "PAYMENT_FAILED" || facts.evidence.paymentFailed > 0) {
    const failure = lastFailure(facts);
    return check(
      "PROVIDER_CAPTURE",
      label,
      "FAILED",
      failure === null ? "Payment did not complete" : `Failed: ${failure}`,
      "No money was taken.",
    );
  }
  if (facts.attempts.length > 0 && !HALTED.has(facts.state)) {
    return check("PROVIDER_CAPTURE", label, "PENDING", "No settlement yet");
  }
  return check("PROVIDER_CAPTURE", label, "NOT_REACHED", "Not reached");
}

function commitCheck(facts: SafetyPassportFacts): PassportCheck {
  const label = "Inventory committed";
  const committedRows = facts.reservationStatuses.filter((s) => s === "COMMITTED").length;
  const commits = facts.evidence.inventoryCommitted;

  if (commits === 0 && committedRows === 0) {
    const captured = hasCapture(facts);
    return check(
      "INVENTORY_COMMITTED",
      label,
      captured ? "PENDING" : "NOT_REACHED",
      captured ? "Not committed yet" : "Not reached",
      "Stock leaves the warehouse only against a confirmed capture, never against a verified callback.",
    );
  }

  // "Exactly once" needs the history and the present to agree: one audit record
  // and one committed row is the only combination that proves it.
  const once = commits === 1 && committedRows === 1;
  return check(
    "INVENTORY_COMMITTED",
    label,
    "COMMITTED",
    once ? "Committed exactly once" : "Committed",
    once
      ? "One commit is recorded in the audit trail, and one reservation carries it."
      : `${String(commits)} commit records and ${String(committedRows)} committed holds are recorded for this purchase.`,
    once ? "POSITIVE" : "WARNING",
  );
}

/**
 * Where each lifecycle state leaves the purchase, as one status.
 *
 * Total over `TransactionState`, so adding a state to the machine without
 * deciding how the passport reports it is a compile error rather than a blank
 * line a reviewer would read as "nothing to see here".
 */
const TRANSACTION_STATUS_OF: Readonly<Record<TransactionState, PassportStatus>> = {
  INTENT_RECEIVED: "PENDING",
  PRODUCT_SELECTED: "PENDING",
  PRODUCT_VERIFIED: "PENDING",
  QUOTE_CREATED: "PENDING",
  POLICY_EVALUATED: "PENDING",
  APPROVAL_REQUIRED: "REQUIRED",
  AUTHORIZED: "ALLOWED",
  INVENTORY_RESERVED: "RESERVED",
  PAYMENT_ORDER_CREATED: "PENDING",
  PAYMENT_PENDING: "PENDING",
  PAYMENT_VERIFIED: "VERIFIED",
  PAYMENT_CAPTURED: "CAPTURED",
  COMPLETED: "COMPLETED",
  PAYMENT_FAILED: "FAILED",
  BLOCKED: "BLOCKED",
  CANCELLED: "STOPPED",
  EXPIRED: "EXPIRED",
};

function transactionCheck(facts: SafetyPassportFacts): PassportCheck {
  return check(
    "TRANSACTION",
    "Transaction",
    TRANSACTION_STATUS_OF[facts.state],
    facts.state,
    facts.state === "COMPLETED"
      ? "Every step above was recorded before this one."
      : HALTED.has(facts.state)
        ? "This purchase stopped here. Nothing further will happen to it."
        : null,
  );
}

// ---------------------------------------------------------------------------
// The retry section
// ---------------------------------------------------------------------------

const ATTEMPT_STATUS_OF: Readonly<Record<string, PassportStatus>> = {
  CREATED: "PENDING",
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  CAPTURED: "CAPTURED",
  FAILED: "FAILED",
  RECONCILIATION_REQUIRED: "PENDING",
};

/**
 * The second section, shown only when there is genuinely something to show.
 *
 * A first-attempt purchase has no retry story, and rendering an empty "retry
 * safety" heading under one would be decoration. Every row below is present
 * only because a persisted row or an audit record put it there.
 */
function buildRetry(facts: SafetyPassportFacts): SafetyPassportViewModel["retry"] {
  const hasHistory =
    facts.attempts.length > 1 ||
    // A single failed attempt counts: "may I try again, and how many times?" is
    // exactly the question a person asks at that point, and the answer is the
    // server's, not the page's.
    facts.attempts.some((attempt) => attempt.status === "FAILED") ||
    facts.evidence.retryRequested > 0 ||
    facts.evidence.quoteReissued > 0 ||
    facts.evidence.webhookDuplicate > 0;
  if (!hasHistory) return null;

  const rows: PassportRow[] = facts.attempts.map((attempt) => {
    const status = ATTEMPT_STATUS_OF[attempt.status] ?? "PENDING";
    const label = STATUS_LABELS[status].toUpperCase();
    return {
      label: `Attempt ${String(attempt.attemptNumber)}`,
      value:
        attempt.failureCategory === null
          ? label
          : `${label} · ${attempt.failureCategory.replace(/_/g, " ").toLowerCase()}`,
      tone: STATUS_TONES[status],
    };
  });

  if (facts.evidence.retryRequested > 0) {
    rows.push({ label: "Retry authority", value: "HUMAN-TRIGGERED", tone: "POSITIVE" });
  }
  if (facts.evidence.quoteReissued > 0) {
    rows.push({ label: "Fresh quote on retry", value: "VERIFIED", tone: "POSITIVE" });
    rows.push({
      label: "Policy re-evaluated",
      value: facts.evidence.policyEvaluated > 1 ? "YES" : "NOT RECORDED",
      tone: facts.evidence.policyEvaluated > 1 ? "POSITIVE" : "NEUTRAL",
    });
  }
  if (facts.evidence.inventoryRequoted > 0) {
    rows.push({ label: "Existing stock hold", value: "REUSED", tone: "POSITIVE" });
  }
  if (facts.evidence.webhookDuplicate > 0) {
    rows.push({
      label: "Duplicate provider event",
      value: "DEDUPLICATED",
      tone: "POSITIVE",
    });
  }
  if (facts.evidence.webhookMismatch > 0) {
    rows.push({ label: "Mismatched provider event", value: "REFUSED", tone: "WARNING" });
  }
  if (facts.retryAvailable !== null) {
    rows.push({
      label: "Retry eligibility",
      value: facts.retryAvailable
        ? "AVAILABLE"
        : (facts.retryDenial ?? "NOT AVAILABLE").replace(/_/g, " "),
      tone: facts.retryAvailable ? "POSITIVE" : "NEUTRAL",
    });
  }

  return { attemptsUsed: facts.attempts.length, maxAttempts: facts.maxAttempts, rows };
}

// ---------------------------------------------------------------------------
// The five properties
// ---------------------------------------------------------------------------

/**
 * The pitch, kept honest.
 *
 * Each property is a claim, so each one carries the evidence from *this*
 * transaction that supports it — and `evidenced` is false when that evidence is
 * absent. A row of five green words that were true of the architecture rather
 * than of the purchase in front of the reader would be marketing, not a
 * passport.
 */
function buildProperties(
  facts: SafetyPassportFacts,
  approval: PassportCheck,
): readonly PassportProperty[] {
  const explainable = facts.evidence.auditedFacts > 0;
  const bounded = facts.evidence.productVerified > 0;
  const gated = facts.policyDecision !== null;
  const auditable = facts.evidence.stateTransitions > 0;
  const failureSafe = facts.evidence.multipleCaptureDetected === 0;

  return [
    {
      label: "Explainable",
      evidenced: explainable,
      evidence: explainable
        ? `${String(facts.evidence.auditedFacts)} decisions recorded, each with the reason code that produced it.`
        : "No decision has been recorded for this purchase yet.",
    },
    {
      label: "Bounded",
      evidenced: bounded,
      evidence: bounded
        ? "The assistant's proposal was checked against the merchant catalog before any amount existed."
        : "No proposal has been verified against the catalog yet.",
    },
    {
      label: "Human-gated when required",
      evidenced: gated,
      evidence: gated
        ? `Policy returned ${String(facts.policyDecision)}; human approval ${approval.statusLabel.toLowerCase()}.`
        : "The spending policy has not been evaluated yet.",
    },
    {
      label: "Auditable",
      evidenced: auditable,
      evidence: auditable
        ? `${String(facts.evidence.stateTransitions)} lifecycle transitions recorded by the state machine.`
        : "No lifecycle transition has been recorded yet.",
    },
    {
      label: "Failure-safe",
      evidenced: failureSafe,
      evidence: failureSafe
        ? `Payment attempts are capped at ${String(facts.maxAttempts)} and counted from stored rows; a redelivered provider event is deduplicated rather than acted on twice.`
        : "More than one captured payment was detected and recorded for review.",
    },
  ];
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export const SAFETY_PASSPORT_TITLE = "Agentic Purchase Safety Passport";

/** Builds the passport for one transaction from facts already read. */
export function buildSafetyPassport(facts: SafetyPassportFacts): SafetyPassportViewModel {
  const approval = approvalCheck(facts);
  const stopped = HALTED.has(facts.state) || facts.state === "PAYMENT_FAILED";

  return {
    transactionId: facts.transactionId,
    title: SAFETY_PASSPORT_TITLE,
    // A stopped purchase does not get a success narrative. The passport is an
    // explainability artefact first and a badge second, and a blocked purchase
    // is exactly the case a reviewer most wants explained.
    subtitle: stopped
      ? "What this AI-assisted purchase was allowed to do, and where it stopped."
      : "Why this AI-assisted purchase was allowed to move forward.",
    aiAuthority: {
      label: "AI authority",
      value: "Product proposal only",
      note: "The assistant proposes a product from the merchant's catalog. It cannot set a price, evaluate policy, approve a purchase, hold stock or move money.",
    },
    financialAuthority: {
      label: "Financial authority",
      value: "Deterministic server",
      note: "Every amount, decision and outcome below was produced by server code and read back from persisted rows.",
    },
    priceSource: "Price source: server-verified merchant data.",
    checks: [
      aiBoundedCheck(facts),
      priceCheck(facts),
      policyCheck(facts),
      approval,
      inventoryCheck(facts),
      paymentAmountCheck(facts),
      callbackCheck(facts),
      captureCheck(facts),
      commitCheck(facts),
      transactionCheck(facts),
    ],
    retry: buildRetry(facts),
    properties: buildProperties(facts, approval),
  };
}
