import { handleProductByIdRequest } from "@/app/api/catalog/handlers";

/**
 * One product by its server-issued id.
 *
 * `RouteContext` is generated by `next typegen`, so the param name is checked
 * against the route path rather than typed by hand.
 */
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  context: RouteContext<"/api/catalog/products/[productId]">,
): Promise<Response> {
  const { productId } = await context.params;
  return handleProductByIdRequest(productId);
}
